# Generated by Django 6.0.8 on 2026-08-27 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='draft', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='projects/favicons/')),
                ('primary_domain', models.CharField(blank=True, db_index=True, max_length=253, null=True, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('tax_config', models.JSONField(blank=True, default=dict)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('email_config', models.JSONField(blank=True, default=dict)),
                ('payment_config', models.JSONField(blank=True, default=dict)),
                ('shipping_config', models.JSONField(blank=True, default=dict)),
                ('seo_config', models.JSONField(blank=True, default=dict)),
                ('notification_config', models.JSONField(blank=True, default=dict)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='projects.project')),
            ],
            options={
                'ordering': ['host'],
            },
        ),
    ]
