# Generated by Django 5.2.17 on 2026-08-27 13:17

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='last_check_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='verification_token',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AddField(
            model_name='domain',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='host',
            field=models.CharField(db_index=True, max_length=253, unique=True, validators=[apps.projects.models.validate_hostname]),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('project',), name='uniq_primary_domain_per_project'),
        ),
    ]
