# Generated by Django 5.2.17 on 2026-08-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_skin_themesettings_skin'),
        ('projects', '0002_domain_last_check_error_domain_last_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allowed_skins',
            field=models.ManyToManyField(blank=True, related_name='projects', to='cms.skin'),
        ),
    ]
