# Generated by Django 5.2.17 on 2026-09-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_mark_existing_stores_onboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
    ]
