# Generated by Django 5.2.17 on 2026-09-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_b2b_seller',
            field=models.BooleanField(default=False),
        ),
    ]
