# Generated by Django 5.2.17 on 2026-09-06 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_is_b2b_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='showcase_review_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='showcase_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='showcase_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_showcase_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='showcase_status',
            field=models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='showcase_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
