# Generated by Django 5.2.17 on 2026-10-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_showcase_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='signup_source',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
