# Generated by Django 5.2.17 on 2026-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_signup_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brand',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
    ]
