# Generated by Django 5.2.17 on 2026-09-24 11:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_archived_at_order_is_archived'),
        ('projects', '0007_project_showcase_review_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], db_index=True, default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commission', to='orders.order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='referrals.referrer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landing_path', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='referrals.referrer')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_attribution', to='orders.order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='referrals.referrer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('commission_type', models.CharField(choices=[('percent', '% of order value'), ('fixed', 'Fixed amount per order')], default='percent', max_length=10)),
                ('commission_value', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='A percent (0-100) or a flat currency amount, depending on Commission type.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cookie_days', models.PositiveIntegerField(default=30, help_text="How long a click keeps crediting a referrer's orders.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('minimum_payout', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Shown to referrers as the payout threshold. Informational only -- payouts are still marked manually by the store owner.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'referral program',
                'constraints': [models.UniqueConstraint(fields=('project',), name='uniq_referralprogram_per_project')],
            },
        ),
        migrations.AddConstraint(
            model_name='referrer',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uniq_referrer_per_user_project'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['referrer', 'status'], name='referrals_r_referre_f4c7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='referralclick',
            index=models.Index(fields=['referrer', 'created_at'], name='referrals_r_referre_ea4c4d_idx'),
        ),
    ]
