# Generated by Django 5.2.17 on 2026-08-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='platform_role',
            field=models.CharField(choices=[('none', 'None'), ('platform_manager', 'Digital Growth Consultant (DGC)'), ('platform_owner', 'Platform Owner')], default='none', max_length=32),
        ),
    ]
