# Generated by Django 5.2.17 on 2026-09-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_partnerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payout_upi',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
