# Generated by Django 5.2.17 on 2026-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_payout_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
