# Generated by Django 5.2.17 on 2026-09-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_affiliate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ui_mode',
            field=models.CharField(choices=[('easy', 'Easy'), ('expert', 'Expert')], default='expert', max_length=6),
        ),
    ]
