# Generated by Django 5.2.17 on 2026-09-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_ui_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_guides',
            field=models.BooleanField(default=True),
        ),
    ]
