# Generated by Django 5.2.17 on 2026-10-01 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_project_showcase_review_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('task', 'Checklist task'), ('tip', 'Tip (did you know?)'), ('message', 'Message from the platform')], default='task', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True, help_text='Longer text — the tip itself, or why this task matters.')),
                ('icon', models.CharField(blank=True, default='✅', help_text='One emoji.', max_length=8)),
                ('auto_key', models.CharField(blank=True, help_text='Tick itself when the store does the thing. Blank = the owner ticks it.', max_length=40)),
                ('target', models.PositiveIntegerField(default=1, help_text='How many (e.g. 5 products). Only used by auto tasks.')),
                ('points', models.PositiveIntegerField(default=10)),
                ('cta_label', models.CharField(blank=True, help_text='Button text, e.g. “Add products”.', max_length=40)),
                ('cta_url', models.CharField(blank=True, help_text="Page to open: /admin/… path or full link. {store_url} = the store's own site.", max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, help_text='Last day it shows. Blank = no end.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(db_index=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='coach.mission')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-day', 'mission_id'],
                'indexes': [models.Index(fields=['project', 'day'], name='coach_missi_project_af7005_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'mission', 'day'), name='uniq_missionlog_day')],
            },
        ),
    ]
