# Generated by Django 5.2.17 on 2026-09-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_product_trashed_at_product_trashed_from_status'),
        ('projects', '0007_project_showcase_review_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, editable=False, max_length=16)),
                ('title', models.CharField(help_text='e.g. “1.02 ct Round Brilliant Diamond”.', max_length=200)),
                ('lab_name', models.CharField(blank=True, help_text='GIA, IGI, SGL, in-house…', max_length=120)),
                ('lab_number', models.CharField(blank=True, db_index=True, help_text='The certificate number printed by the lab.', max_length=120)),
                ('gem_type', models.CharField(blank=True, max_length=80)),
                ('carat_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('shape_cut', models.CharField(blank=True, max_length=80)),
                ('color_grade', models.CharField(blank=True, max_length=40)),
                ('clarity_grade', models.CharField(blank=True, max_length=40)),
                ('measurements', models.CharField(blank=True, max_length=120)),
                ('metal', models.CharField(blank=True, help_text='18K Gold, Platinum 950…', max_length=80)),
                ('gross_weight', models.CharField(blank=True, max_length=40)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('image_front', models.ImageField(upload_to='certificates/')),
                ('image_back', models.ImageField(blank=True, upload_to='certificates/')),
                ('is_public', models.BooleanField(default=True, help_text='Off = the code stops verifying on the storefront.')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='catalog.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'code'), name='uniq_certificate_code')],
            },
        ),
    ]
