# Generated by Django 5.2.17 on 2026-08-28 09:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_allowed_skins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_key_id', models.CharField(blank=True, max_length=120)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=200)),
                ('razorpay_webhook_secret', models.CharField(blank=True, max_length=200)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('grace_days', models.PositiveIntegerField(default=7, help_text='Days after due date before suspend.')),
                ('invoice_prefix', models.CharField(default='INV', max_length=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('default_commission_monthly_pct', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5)),
                ('default_commission_yearly_pct', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5)),
            ],
            options={
                'verbose_name': 'billing settings',
                'verbose_name_plural': 'billing settings',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], db_index=True, default='open', max_length=14)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider_order_id', models.CharField(blank=True, max_length=120)),
                ('provider_payment_id', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Shown on the plan picker.')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total for 12 months.', max_digits=12)),
                ('commission_monthly_pct', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5)),
                ('commission_yearly_pct', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5)),
                ('max_products', models.PositiveIntegerField(blank=True, null=True)),
                ('max_staff', models.PositiveIntegerField(blank=True, null=True)),
                ('max_custom_domains', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_skin_upload', models.BooleanField(default=False)),
                ('remove_platform_branding', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('transaction_fee_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Platform fee on storefront sales, %.', max_digits=5)),
                ('features', models.JSONField(blank=True, default=list, help_text='Marketing bullet list.')),
            ],
            options={
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='trialing', max_length=12)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField(db_index=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], db_index=True, default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payout_ref', models.CharField(blank=True, max_length=120)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='billing.invoice')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_at'], name='billing_inv_status_bc0902_idx'),
        ),
    ]
