# Generated by Django 5.2.17 on 2026-08-31 07:55

from decimal import Decimal

from django.db import migrations, models


def bump_to_30(apps, schema_editor):
    """DGC marketing-partner commission is a flat 30% of the subscription fee.
    Only rows still on the old 20% monthly default are moved."""
    apps.get_model("billing", "Plan").objects.filter(
        commission_monthly_pct=Decimal("20")
    ).update(commission_monthly_pct=Decimal("30"))
    apps.get_model("billing", "BillingSettings").objects.filter(
        default_commission_monthly_pct=Decimal("20")
    ).update(default_commission_monthly_pct=Decimal("30"))


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_backfill_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsettings',
            name='default_commission_monthly_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='commission_monthly_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5),
        ),
        migrations.RunPython(bump_to_30, migrations.RunPython.noop),
    ]
