# Generated by Django 5.2.17 on 2026-09-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billingsettings_self_signup_trial_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_comp',
            field=models.BooleanField(default=False, help_text='Gifted store — free, no invoices, never suspended.'),
        ),
    ]
