# Generated by Django 5.2.17 on 2026-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_subscription_is_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='affiliate_ref',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
