# Generated by Django 5.2.17 on 2026-09-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_backfill_affiliate_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
