# Generated by Django 5.2.17 on 2026-09-18 15:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_subscription_trial_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='dgc_price_monthly',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='plan',
            name='dgc_price_yearly',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total for 12 months.', max_digits=12),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billed_to_dgc',
            field=models.BooleanField(default=False),
        ),
    ]
