# Generated by Django 5.2.17 on 2026-09-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_new_plan_pricing_and_dgc_wholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allow_full_backup',
            field=models.BooleanField(default=False),
        ),
    ]
