# Generated by Django 5.2.17 on 2026-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_row',
            field=models.CharField(choices=[('below', 'In the row below the hero'), ('top', 'In the row above the hero'), ('both', 'Both rows'), ('none', 'Not on the home page')], default='below', help_text='Where this category tile shows in the home-page category rows (the top row needs a skin that supports it, e.g. Botanica 3.0).', max_length=10),
        ),
    ]
