# Generated by Django 5.2.17 on 2026-09-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='recovery_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
