# Generated by Django 5.2.17 on 2026-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(db_index=True, help_text='Videos are grouped under this heading.', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.CharField(help_text='Paste the YouTube link.', max_length=300)),
                ('youtube_id', models.CharField(blank=True, editable=False, max_length=20)),
                ('duration_label', models.CharField(blank=True, help_text='e.g. “7 min”.', max_length=20)),
                ('audience', models.JSONField(blank=True, default=list, help_text='Which roles see this video.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['topic', 'order', 'title'],
            },
        ),
    ]
