# Generated by Django 5.2.17 on 2026-09-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_project_showcase_review_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBackupSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.FileField(upload_to='backups/%Y/%m/%d/')),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_snapshots', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
