# Generated by Django 5.2.17 on 2026-10-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebackupsnapshot',
            name='includes_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storebackupsnapshot',
            name='label',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
