# Generated by Django 5.2.17 on 2026-09-10 08:15

import apps.whatsapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_project_showcase_review_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('waba_id', models.CharField(blank=True, max_length=64, verbose_name='WhatsApp Business Account ID')),
                ('access_token', models.CharField(blank=True, max_length=512)),
                ('app_secret', models.CharField(blank=True, max_length=128)),
                ('verify_token', models.CharField(default=apps.whatsapp.models._new_verify_token, max_length=64)),
                ('graph_version', models.CharField(default='v21.0', max_length=8)),
                ('display_phone', models.CharField(blank=True, max_length=32)),
                ('verified_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'WhatsApp account',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_number', models.CharField(db_index=True, max_length=32)),
                ('wamid', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField(blank=True)),
                ('is_opt_out', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound', to='whatsapp.whatsappaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_number', models.CharField(max_length=32)),
                ('wamid', models.CharField(blank=True, db_index=True, max_length=128)),
                ('kind', models.CharField(default='template', max_length=12)),
                ('template_name', models.CharField(blank=True, max_length=120)),
                ('event', models.CharField(blank=True, max_length=40)),
                ('body_preview', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('accepted', 'Accepted by Meta'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=12)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('related_type', models.CharField(blank=True, max_length=60)),
                ('related_id', models.CharField(blank=True, max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='whatsappaccount',
            constraint=models.UniqueConstraint(fields=('project',), name='uniq_whatsapp_account_per_project'),
        ),
    ]
