# Generated by Django 5.2.17 on 2026-09-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_showcase_review_note_and_more'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='whatsappaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number_id', ''), _negated=True), fields=('phone_number_id',), name='uniq_whatsapp_phone_number_id'),
        ),
    ]
