# Generated by Django 5.2.17 on 2026-10-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(blank=True, help_text='e.g. “Owner, Nisha Boutique, Pune”.', max_length=120)),
                ('pages', models.JSONField(blank=True, default=list, help_text='Landing-page slugs this quote appears on. Leave empty for all pages.')),
                ('consent_confirmed', models.BooleanField(default=False, help_text="I have this seller's permission to publish their name and words.")),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
