# Generated by Django 5.2.17 on 2026-08-27 10:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('released', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount'), ('free_shipping', 'Free shipping')], default='percent', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percent (0-100) or fixed amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage discounts.', max_digits=12, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('applies_to', models.CharField(choices=[('all', 'Whole order'), ('products', 'Specific products'), ('categories', 'Specific categories')], default='all', max_length=20)),
                ('first_order_only', models.BooleanField(default=False)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit_per_customer', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='coupons', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
