# Generated by Django 5.2.17 on 2026-08-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_rating_avg_product_rating_count'),
        ('coupons', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0003_order_customer'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='customer_groups',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='customers.customergroup'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='uniq_coupon_code_per_project'),
        ),
    ]
