# Generated by Django 5.2.17 on 2026-10-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='stores/upi-qr/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('payu', 'PayU'), ('manual', 'Manual / offline'), ('upi', 'UPI (QR / direct)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentproviderconfig',
            name='provider',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('payu', 'PayU'), ('manual', 'Manual / offline'), ('upi', 'UPI (QR / direct)')], max_length=20),
        ),
    ]
