# Generated by Django 5.2.17 on 2026-08-27 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_path', models.CharField(db_index=True, max_length=300)),
                ('to_path', models.CharField(max_length=300)),
                ('is_permanent', models.BooleanField(default=True, help_text='301 when on, 302 when off.')),
                ('is_active', models.BooleanField(default=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['from_path'],
                'constraints': [models.UniqueConstraint(fields=('project', 'from_path'), name='uniq_redirect_from_path')],
            },
        ),
        migrations.CreateModel(
            name='SeoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('canonical', models.CharField(blank=True, max_length=300)),
                ('og_title', models.CharField(blank=True, max_length=180)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('robots', models.CharField(blank=True, max_length=60)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['path'],
                'constraints': [models.UniqueConstraint(fields=('project', 'path'), name='uniq_seometa_path')],
            },
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_suffix', models.CharField(blank=True, help_text="Appended to page titles, e.g. ' | My Store'.", max_length=120)),
                ('default_description', models.CharField(blank=True, max_length=320)),
                ('default_og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('default_robots', models.CharField(default='index,follow', max_length=60)),
                ('twitter_handle', models.CharField(blank=True, max_length=60)),
                ('google_site_verification', models.CharField(blank=True, max_length=120)),
                ('facebook_app_id', models.CharField(blank=True, max_length=60)),
                ('organization_schema', models.JSONField(blank=True, default=dict)),
                ('sitemap_enabled', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'SEO settings',
                'verbose_name_plural': 'SEO settings',
                'constraints': [models.UniqueConstraint(fields=('project',), name='uniq_seosettings_per_project')],
            },
        ),
    ]
