# Generated by Django 5.2.17 on 2026-09-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_project_showcase_review_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('meta', 'Meta Pixel'), ('ga4', 'Google Analytics 4'), ('tiktok', 'TikTok Pixel')], max_length=16)),
                ('pixel_id', models.CharField(max_length=64)),
                ('server_token', models.CharField(blank=True, max_length=512)),
                ('test_event_code', models.CharField(blank=True, max_length=64)),
                ('track_browser', models.BooleanField(default=True)),
                ('track_server', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['provider'],
                'constraints': [models.UniqueConstraint(fields=('project', 'provider'), name='uniq_tracking_provider_per_project')],
            },
        ),
    ]
