# Generated by Django 5.2.17 on 2026-09-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTrackingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_pixel_id', models.CharField(blank=True, max_length=64)),
                ('ga4_measurement_id', models.CharField(blank=True, max_length=32)),
                ('tiktok_pixel_id', models.CharField(blank=True, max_length=64)),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch — off = inject nothing.')),
            ],
            options={
                'verbose_name': 'platform tracking settings',
                'verbose_name_plural': 'platform tracking settings',
            },
        ),
    ]
