# Generated by Django 5.2.17 on 2026-09-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_platformtrackingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtrackingsettings',
            name='meta_capi_token',
            field=models.CharField(blank=True, help_text='Events Manager → your pixel → Settings → Conversions API → Generate access token.', max_length=512, verbose_name='Meta Conversions API access token'),
        ),
        migrations.AddField(
            model_name='platformtrackingsettings',
            name='meta_test_event_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
