# Generated by Django 5.2.17 on 2026-10-02 06:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0016_growth_and_pro_get_full_backup'),
        ('projects', '0008_project_signup_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('business', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(blank=True, help_text='Cold call, referral, ad…', max_length=60)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('demo_booked', 'Demo booked'), ('demo_done', 'Demo done'), ('negotiating', 'Negotiating'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=14)),
                ('notes', models.TextField(blank=True)),
                ('next_follow_up', models.DateField(blank=True, db_index=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('subscription', 'Subscription invoice'), ('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank transfer')], max_length=14)),
                ('reference', models.CharField(blank=True, help_text='UTR / receipt no.', max_length=120)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='crm/proof/')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('collected_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_collections', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_collection', to='billing.invoice')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='crm.lead')),
            ],
            options={
                'ordering': ['-collected_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreWorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('catalog', 'Product entry'), ('maintenance', 'Store maintenance')], default='catalog', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=10)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_work', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('due_on', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=10)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_tasks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.lead')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project')),
            ],
            options={
                'ordering': ['status', 'due_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(blank=True, max_length=160)),
                ('trained_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('pending', 'Awaiting trainer'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_trainings', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_trained', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trained_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(choices=[('calls', 'Calls / day'), ('demos', 'Demos / day'), ('collection', 'Collection ₹ / day')], max_length=12)),
                ('value', models.PositiveIntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'metric'), name='crm_target_user_metric')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('demo', 'Demo given'), ('follow_up', 'Follow-up'), ('store_setup', 'Store set-up'), ('product_entry', 'Product entry'), ('maintenance', 'Store maintenance')], db_index=True, max_length=14)),
                ('outcome', models.CharField(blank=True, choices=[('connected', 'Connected'), ('not_reachable', 'Not reachable'), ('no_answer', 'No answer'), ('call_back', 'Asked to call back'), ('not_interested', 'Not interested'), ('done', 'Done')], max_length=14)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('count', models.PositiveIntegerField(default=1, help_text='e.g. products entered in one go.')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.lead')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['actor', 'kind', 'occurred_at'], name='crm_activit_actor_i_ac3091_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('catalog', 'Product entry'), ('maintenance', 'Store maintenance')], default='catalog', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_assignments', to='projects.project')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='crm.storeworkrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'assignee', 'scope'), name='crm_one_active_assignment')],
            },
        ),
    ]
