# Generated by Django 5.2.17 on 2026-10-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stage_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('demo', 'Demo given'), ('follow_up', 'Follow-up'), ('store_setup', 'Store set-up'), ('product_entry', 'Product entry'), ('maintenance', 'Store maintenance'), ('stage_change', 'Stage change')], db_index=True, max_length=14),
        ),
    ]
