# Generated by Django 5.2.17 on 2026-10-03 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_initiated_by(apps, schema_editor):
    """Every training logged before this migration was created by the trainee
    ("I was trained by X"), so the trainer is the one who confirms."""
    TrainingLog = apps.get_model("crm", "TrainingLog")
    TrainingLog.objects.filter(initiated_by__isnull=True, trainee__isnull=False).update(
        initiated_by=models.F("trainee"))


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglog',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traininglog',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traininglog',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traininglog',
            name='student_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='traininglog',
            name='student_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='status',
            field=models.CharField(choices=[('requested', 'Wants training'), ('assigned', 'Trainer assigned'), ('pending', 'Awaiting confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_trained', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_initiated_by, migrations.RunPython.noop),
    ]
