# Generated by Django 5.2.17 on 2026-10-06 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_phone_norm(apps, schema_editor):
    """Same rule as apps.crm.models.normalize_phone (kept inline: migrations must
    not import app code that may change later)."""
    Lead = apps.get_model("crm", "Lead")
    for lead in Lead.objects.exclude(phone="").filter(phone_norm="").iterator():
        digits = "".join(c for c in lead.phone if c.isdigit())
        lead.phone_norm = digits[-10:] if len(digits) >= 10 else digits
        lead.save(update_fields=["phone_norm"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_training_flows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_assign', models.BooleanField(default=True, help_text='Hand new inbound leads to a DGC instantly.')),
                ('capacity_per_dgc', models.PositiveIntegerField(default=0, help_text='Max open leads per DGC for auto-assign. 0 = no limit.')),
                ('alert_email', models.BooleanField(default=True, help_text='Email the DGC when a lead is assigned to them.')),
                ('trial_rescue_days', models.PositiveSmallIntegerField(default=3, help_text="Create a task this many days before a DGC's store trial ends. 0 = off.")),
                ('health_no_products_days', models.PositiveSmallIntegerField(default=7, help_text="Task if a DGC's store still has no products after this many days. 0 = off.")),
                ('health_no_orders_days', models.PositiveSmallIntegerField(default=14, help_text='Task if a live store has no orders after this many days. 0 = off.')),
                ('recycle_days', models.PositiveSmallIntegerField(default=30, help_text='Return untouched open leads to the pool after this many days. 0 = off.')),
                ('quiet_check', models.BooleanField(default=True, help_text='Email admins when a DGC has done nothing by midday.')),
                ('quiet_after_hour', models.PositiveSmallIntegerField(default=12, help_text='Local hour (0-23) the quiet check runs after.')),
                ('weekly_digest', models.BooleanField(default=True, help_text='Email a team summary every Monday.')),
                ('digest_emails', models.TextField(blank=True, help_text="Comma-separated. Blank = every platform admin's email.")),
                ('avg_plan_price', models.DecimalField(decimal_places=2, default=2999, help_text='Average monthly plan price used for the revenue forecast.', max_digits=10)),
                ('stage_probabilities', models.JSONField(blank=True, default=dict, help_text='Chance (%) a lead at each stage becomes a paying store.')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='acquisition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='auto_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='demo_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_touch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_norm',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.CreateModel(
            name='CrmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepts_leads', models.BooleanField(default=True, help_text='Off = skipped by auto-assign (e.g. on leave).')),
                ('cities', models.CharField(blank=True, help_text='Cities / areas this DGC covers, comma-separated. New leads from these go to them first.', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RunPython(backfill_phone_norm, migrations.RunPython.noop),
    ]
