# Generated by Django 5.2.17 on 2026-10-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_intake_routing_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmsettings',
            name='last_digest_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='crmsettings',
            name='last_quiet_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
