# Generated by Django 5.2.17 on 2026-10-06 06:54

from django.db import migrations, models


SEED = [
    ("whatsapp", "", "Intro", 10,
     "Hi {first_name}, this is {dgc} from ShopInADay 👋 We help shop owners like {business} start selling online "
     "in a day — no tech skills needed. Can I show you a quick 5-minute demo?"),
    ("whatsapp", "", "Demo link", 20,
     "Hi {first_name}, here's a sample so you can see how your store could look: https://shopinaday.com/ — "
     "want me to set up yours on a free trial?"),
    ("whatsapp", "", "Pricing", 30,
     "Hi {first_name}, you get a free trial first, so you can try everything before you pay. "
     "Shall I share the plan details for {business}?"),
    ("whatsapp", "", "Follow-up", 40,
     "Hi {first_name}, just checking in — did you get a chance to look at ShopInADay? "
     "Happy to help you get your first products online today."),
    ("script", "new", "Opening call", 10,
     "Hello, am I speaking with {name}? I'm {dgc} from ShopInADay. We help shops like {business} sell online "
     "in a day. Do you have 2 minutes?\n\nIf yes → ask what they sell and how they take orders today. "
     "If busy → ask for a better time and tap 'Call back later'."),
    ("script", "interested", "Book the demo", 10,
     "Offer a 5-minute demo: \"I'll set up your store with your own products on a free trial so you see it "
     "working before paying anything.\"\n\nFix a time, then use 'Book a demo' on this page."),
    ("script", "negotiating", "Handling objections", 10,
     "Too expensive → start with the free trial; they pay only once orders come.\n"
     "No time → we do the product entry for you.\nNot tech-savvy → it's as simple as WhatsApp; stay with them "
     "on the first day.\nNeed to ask someone → offer to call back with the decision-maker on the line."),
]


def seed_templates(apps, schema_editor):
    Template = apps.get_model("crm", "MessageTemplate")
    if Template.objects.exists():
        return
    for kind, stage, title, order, body in SEED:
        Template.objects.create(kind=kind, stage=stage, title=title, order=order, body=body)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_automation_bookkeeping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('whatsapp', 'WhatsApp message'), ('script', 'Call script')], default='whatsapp', max_length=10)),
                ('stage', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('demo_booked', 'Demo booked'), ('demo_done', 'Demo done'), ('negotiating', 'Negotiating'), ('won', 'Won'), ('lost', 'Lost')], help_text='Scripts only: show for leads at this stage. Blank = every stage.', max_length=14)),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField(max_length=2000)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourceSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, max_length=60)),
                ('month', models.DateField(help_text='Any date in the month.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['-month', 'source'],
                'constraints': [models.UniqueConstraint(fields=('source', 'month'), name='crm_spend_source_month')],
            },
        ),
        migrations.RunPython(seed_templates, migrations.RunPython.noop),
    ]
