# Generated by Django 5.2.17 on 2026-10-06 08:07

import apps.crm.tz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_templates_and_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collected_on',
            field=models.DateField(db_index=True, default=apps.crm.tz.biz_today),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='trained_on',
            field=models.DateField(db_index=True, default=apps.crm.tz.biz_today),
        ),
    ]
