# Generated by Django 5.2.17 on 2026-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_india_time_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmsettings',
            name='conv_call_to_demo',
            field=models.PositiveSmallIntegerField(default=10, help_text='Of every 100 calls, how many become a meeting / demo (%).'),
        ),
        migrations.AddField(
            model_name='crmsettings',
            name='conv_demo_to_trial',
            field=models.PositiveSmallIntegerField(default=60, help_text='Of the meetings / demos, how many start a free trial (%).'),
        ),
        migrations.AddField(
            model_name='crmsettings',
            name='conv_trial_to_paid',
            field=models.PositiveSmallIntegerField(default=50, help_text='Of the trials, how many become paying clients with proper follow-up (%).'),
        ),
        migrations.AddField(
            model_name='crmsettings',
            name='min_ticket_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum monthly plan price used in DGC earnings estimates. Blank = the cheapest public plan.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='crmsettings',
            name='working_days_month',
            field=models.PositiveSmallIntegerField(default=26, help_text='Working days per month used in the monthly projection.'),
        ),
    ]
