# Generated by Django 5.2.17 on 2026-10-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_funnel_assumptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmprofile',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Your own service charge per client (₹), added to your earnings estimates.', max_digits=10),
        ),
        migrations.AddField(
            model_name='crmsettings',
            name='value_commission_pct',
            field=models.PositiveSmallIntegerField(default=20, help_text="The share of a client's YEARLY plan amount counted as a DGC's earning in the estimates (%). Estimates only — real commission follows each plan's setting."),
        ),
        migrations.AlterField(
            model_name='crmsettings',
            name='min_ticket_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Smallest YEARLY plan amount used in the estimates. Blank = the cheapest public plan's yearly price.", max_digits=10, null=True),
        ),
    ]
