# Generated by Django 5.2.17 on 2026-10-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_client_value_yearly'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmprofile',
            name='commission_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text="% of the DGC price counted as this DGC's earning per client.", null=True),
        ),
        migrations.AddField(
            model_name='crmprofile',
            name='conv_call_to_demo',
            field=models.PositiveSmallIntegerField(blank=True, help_text="% of this DGC's calls that become a meeting/demo.", null=True),
        ),
        migrations.AddField(
            model_name='crmprofile',
            name='conv_demo_to_trial',
            field=models.PositiveSmallIntegerField(blank=True, help_text="% of this DGC's meetings/demos that start a trial.", null=True),
        ),
        migrations.AddField(
            model_name='crmprofile',
            name='conv_trial_to_paid',
            field=models.PositiveSmallIntegerField(blank=True, help_text="% of this DGC's trials that become paying clients.", null=True),
        ),
        migrations.AlterField(
            model_name='crmsettings',
            name='min_ticket_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Smallest YEARLY DGC price used in the estimates. Blank = the cheapest plan's DGC yearly price.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crmsettings',
            name='value_commission_pct',
            field=models.PositiveSmallIntegerField(default=20, help_text="The share of the YEARLY DGC price (not the public price) counted as a DGC's earning per client (%). A DGC can have their own on their person page. Estimates only."),
        ),
    ]
