# Generated by Django 5.2.17 on 2026-09-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
