# Generated by Django 5.2.17 on 2026-09-16 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_showcase_review_note_and_more'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.CharField(choices=[('manual', 'Manual / offline'), ('shiprocket', 'Shiprocket'), ('delhivery', 'Delhivery')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_test_mode', models.BooleanField(default=True, help_text='Test mode uses synthetic tracking numbers — no real API call, nothing gets booked at the courier. Turn off once your credentials are live and verified.')),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'courier config',
                'verbose_name_plural': 'courier configs',
                'ordering': ['courier'],
                'constraints': [models.UniqueConstraint(fields=('project', 'courier'), name='uniq_courierconfig_per_project')],
            },
        ),
    ]
