# Generated by Django 5.2.17 on 2026-08-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_rating_avg_product_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='optimized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='original',
            field=models.ImageField(blank=True, upload_to='products/originals/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='renditions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
