# Generated by Django 5.2.17 on 2026-08-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage_bytes_productimage_height_and_more'),
        ('categories', '0001_initial'),
        ('projects', '0003_project_allowed_skins'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                fields=['project', 'status', 'search_indexed', '-created_at'],
                name='catalog_prod_feed_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                fields=['project', 'category', 'status'],
                name='catalog_prod_cat_idx',
            ),
        ),
    ]
