# Generated by Django 5.2.17 on 2026-09-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_catalog_prod_feed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='trashed_from_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
