# Generated by Django 5.2.17 on 2026-09-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_trashed_at_product_trashed_from_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_variant_stock',
            field=models.BooleanField(default=False, help_text="Enforce stock limits for this product's Size/Colour variants."),
        ),
    ]
