# Generated by Django 5.2.17 on 2026-08-27 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('placement', models.CharField(choices=[('hero', 'Hero'), ('promo', 'Promotional'), ('category', 'Category'), ('product', 'Product'), ('popup', 'Popup'), ('announcement', 'Announcement bar')], default='hero', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='banners/')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=300)),
                ('cta_label', models.CharField(blank=True, max_length=60)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='categories.category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['placement', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(blank=True, help_text='Optional grouping heading.', max_length=80)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['group', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(choices=[('main', 'Main menu'), ('footer', 'Footer menu'), ('mobile', 'Mobile menu'), ('category', 'Category menu')], default='main', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('privacy', 'Privacy policy'), ('terms', 'Terms & conditions'), ('return_policy', 'Return policy'), ('shipping_policy', 'Shipping policy'), ('faq', 'FAQ'), ('custom', 'Custom page')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], db_index=True, default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('show_in_sitemap', models.BooleanField(default=True)),
                ('template_key', models.CharField(blank=True, help_text='Frontend layout hint.', max_length=60)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('link_type', models.CharField(choices=[('url', 'Internal URL / path'), ('page', 'CMS page'), ('category', 'Category'), ('external', 'External URL')], default='url', max_length=20)),
                ('url', models.CharField(blank=True, max_length=400)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='categories.category')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='cms.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#111111', max_length=9)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=9)),
                ('accent_color', models.CharField(default='#2563eb', max_length=9)),
                ('font_body', models.CharField(blank=True, max_length=120)),
                ('font_heading', models.CharField(blank=True, max_length=120)),
                ('header_layout', models.CharField(blank=True, max_length=40)),
                ('footer_layout', models.CharField(blank=True, max_length=40)),
                ('button_style', models.CharField(blank=True, max_length=40)),
                ('product_card_style', models.CharField(blank=True, max_length=40)),
                ('homepage_sections', models.JSONField(blank=True, default=list)),
                ('tokens', models.JSONField(blank=True, default=dict)),
                ('custom_css', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'theme settings',
                'verbose_name_plural': 'theme settings',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text="Referenced by the frontend, e.g. 'home-hero'.", max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('block_type', models.CharField(choices=[('hero', 'Hero'), ('richtext', 'Rich text'), ('image', 'Image'), ('video', 'Video'), ('button', 'Button'), ('section', 'Section'), ('grid', 'Grid'), ('html', 'Raw HTML')], default='richtext', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('project', 'key'), name='uniq_contentblock_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='uniq_page_slug_per_project'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'custom'), _negated=True), fields=('project', 'kind'), name='uniq_page_kind_per_project'),
        ),
        migrations.AddConstraint(
            model_name='themesettings',
            constraint=models.UniqueConstraint(fields=('project',), name='uniq_theme_per_project'),
        ),
    ]
