# Generated by Django 5.2.17 on 2026-08-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='skins/previews/')),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True, help_text='Available for stores to use.')),
                ('is_default', models.BooleanField(default=False, help_text='Used when a store has not picked a skin.')),
            ],
            options={
                'ordering': ['label'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uniq_default_skin')],
            },
        ),
        migrations.AddField(
            model_name='themesettings',
            name='skin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_settings', to='cms.skin'),
        ),
    ]
