# Generated by Django 5.2.17 on 2026-08-28 07:18

import apps.cms.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_seed_default_skin'),
        ('projects', '0003_project_allowed_skins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='author',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skin',
            name='is_sandboxed',
            field=models.BooleanField(default=False, help_text='Render in the restricted sandbox environment.'),
        ),
        migrations.AddField(
            model_name='skin',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The store that uploaded this skin. Blank = shared / built-in.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_skins', to='projects.project'),
        ),
        migrations.AddField(
            model_name='skin',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skin',
            name='source',
            field=models.CharField(choices=[('builtin', 'Built-in (developer)'), ('upload', 'Uploaded')], default='builtin', max_length=12),
        ),
        migrations.AddField(
            model_name='skin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=12),
        ),
        migrations.AddField(
            model_name='skin',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skin',
            name='version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SkinAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=160)),
                ('file', models.FileField(max_length=255, upload_to=apps.cms.models._skin_asset_path)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='cms.skin')),
            ],
            options={
                'ordering': ['path'],
                'constraints': [models.UniqueConstraint(fields=('skin', 'path'), name='uniq_skinasset_path')],
            },
        ),
        migrations.CreateModel(
            name='SkinFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cms.skin')),
            ],
            options={
                'ordering': ['path'],
                'constraints': [models.UniqueConstraint(fields=('skin', 'path'), name='uniq_skinfile_path')],
            },
        ),
    ]
