# Generated by Django 5.2.17 on 2026-08-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_sanitize_rich_html'),
        ('projects', '0003_project_allowed_skins'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, upload_to='stores/logos/')),
                ('tagline', models.CharField(blank=True, help_text='Short line under the logo in the footer.', max_length=200)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=32)),
                ('whatsapp', models.CharField(blank=True, help_text='Number in international format, e.g. +9198…', max_length=32)),
                ('address', models.TextField(blank=True, help_text='Full postal address, shown in the footer.')),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True, verbose_name='X / Twitter URL')),
                ('copyright_text', models.CharField(blank=True, help_text='Footer copyright line. Defaults to “© <year> <store name>”.', max_length=200)),
                ('show_payment_icons', models.BooleanField(default=True, help_text='Show accepted-payment icons in the footer.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'store profile',
                'verbose_name_plural': 'store profiles',
                'constraints': [models.UniqueConstraint(fields=('project',), name='uniq_storeprofile_per_project')],
            },
        ),
    ]
