# Generated by Django 5.2.17 on 2026-09-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_seed_botanica2_skin'),
        ('projects', '0007_project_showcase_review_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UGCVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_url', models.URLField(help_text='A YouTube Shorts (or any YouTube video) link.', max_length=300)),
                ('youtube_id', models.CharField(blank=True, editable=False, max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('link_url', models.CharField(blank=True, help_text='Optional — where tapping the video sends a shopper, e.g. a product page.', max_length=300)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'UGC / Shorts video',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
