# Generated by Django 5.2.17 on 2026-09-08 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_backfill_ugcvideo_youtube_id'),
        ('projects', '0007_project_showcase_review_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g. "Under ₹499"', max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='budget_bands/')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Lowest price in this band. Leave blank for no lower bound.', max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Highest price in this band. Leave blank for no upper bound.', max_digits=12, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'budget band',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InstagramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='instagram/')),
                ('source_url', models.URLField(blank=True, help_text='The public Instagram post URL.', max_length=400)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('link_url', models.CharField(blank=True, help_text='Where a tap sends a shopper. Defaults to the post URL.', max_length=400)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'Instagram item',
                'ordering': ['order', 'id'],
            },
        ),
    ]
