# Generated by Django 5.2.17 on 2026-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_rename_kapiva_skin_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text_hidden',
            field=models.BooleanField(default=False, help_text='Show only the image — hide the heading, text and button.'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='category_above_hero',
            field=models.BooleanField(default=False),
        ),
    ]
