# Generated by Django 5.2.17 on 2026-09-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_banner_text_hidden_themesettings_category_above_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='show_category_headings',
            field=models.BooleanField(default=False),
        ),
    ]
