# Generated by Django 5.2.17 on 2026-09-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_benefititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
