# Generated by Django 5.2.17 on 2026-09-14 08:00

from django.db import migrations, models


def _backfill_hide_cta(apps, schema_editor):
    """`text_hidden=True` used to hide the button too (it wrapped the whole
    text+button block). Now the button has its own `hide_cta` flag — keep
    existing banners looking exactly as they did before this split."""
    Banner = apps.get_model("cms", "Banner")
    Banner.objects.filter(text_hidden=True).update(hide_cta=True)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_storeprofile_city_storeprofile_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='hide_cta',
            field=models.BooleanField(default=False, help_text='Hide just the button — keep the heading/subheading if shown.'),
        ),
        migrations.AddField(
            model_name='banner',
            name='hide_overlay',
            field=models.BooleanField(default=False, help_text='Show the image with no dark tint behind the text (may make text harder to read).'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_hidden',
            field=models.BooleanField(default=False, help_text='Hide the heading and subheading text. The button is controlled separately.'),
        ),
        migrations.RunPython(_backfill_hide_cta, migrations.RunPython.noop),
    ]
