# Generated by Django 5.2.17 on 2026-09-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_banner_hide_cta_banner_hide_overlay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='heading_align',
            field=models.CharField(blank=True, choices=[('', "Default (skin's own)"), ('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='heading_font',
            field=models.CharField(choices=[('display', "Skin's display font (default)"), ('sans', "Skin's body font")], default='display', max_length=10),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='heading_size',
            field=models.CharField(choices=[('sm', 'Small'), ('md', 'Medium (default)'), ('lg', 'Large'), ('xl', 'Extra large')], default='md', max_length=6),
        ),
    ]
