# Generated by Django 5.2.17 on 2026-09-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_themesettings_heading_align_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='products_per_row',
            field=models.PositiveSmallIntegerField(choices=[(4, '4 per row'), (5, '5 per row')], default=4),
        ),
    ]
