# Generated by Django 5.2.17 on 2026-09-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_themesettings_products_per_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='section_titles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
