# Generated by Django 5.2.17 on 2026-09-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_themesettings_section_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='hide_featured_eyebrow',
            field=models.BooleanField(default=False),
        ),
    ]
