# Generated by Django 5.2.17 on 2026-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_themesettings_hide_featured_eyebrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Small square image — the icon shown in the browser tab. Falls back to the logo if not set.', upload_to='stores/favicons/'),
        ),
    ]
