# Generated by Django 5.2.17 on 2026-09-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_storeprofile_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='products_shown',
            field=models.PositiveSmallIntegerField(choices=[(5, '5'), (8, '8 (default)'), (10, '10'), (15, '15'), (20, '20')], default=8),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='products_per_row',
            field=models.PositiveSmallIntegerField(choices=[(3, '3 per row'), (4, '4 per row'), (5, '5 per row'), (6, '6 per row')], default=4),
        ),
    ]
