# Generated by Django 5.2.17 on 2026-09-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_themesettings_products_shown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='category_mobile_slider',
            field=models.BooleanField(default=False),
        ),
    ]
