# Generated by Django 5.2.17 on 2026-09-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_themesettings_category_mobile_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video_url',
            field=models.URLField(blank=True, help_text='Hero placement only — paste a YouTube link to play a muted, looping video behind the text instead of the image.', max_length=300),
        ),
        migrations.AddField(
            model_name='banner',
            name='video_youtube_id',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
