# Generated by Django 5.2.17 on 2026-09-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_banner_video_url_banner_video_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='mobile_video_url',
            field=models.URLField(blank=True, help_text='Optional — a different YouTube link for phone screens. Leave blank to use the video above on mobile too.', max_length=300),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_video_youtube_id',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
