# Generated by Django 5.2.17 on 2026-09-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_banner_mobile_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefititem',
            name='kind',
            field=models.CharField(choices=[('why', 'Why it works'), ('trust', 'Trust strip')], default='why', max_length=10),
        ),
    ]
