# Generated by Django 5.2.17 on 2026-09-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_benefititem_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefititem',
            name='kind',
            field=models.CharField(blank=True, choices=[('why', 'Why it works'), ('trust', 'Trust strip')], default='why', max_length=10),
        ),
    ]
