# Generated by Django 5.2.17 on 2026-09-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_alter_benefititem_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='whatsapp_enquiry_enabled',
            field=models.BooleanField(default=False, help_text='Show a WhatsApp button next to Add to cart on every product card, pre-filled with the product name, price and link.'),
        ),
    ]
