# Generated by Django 5.2.17 on 2026-09-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_storeprofile_whatsapp_enquiry_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='whatsapp_enquiry_on_detail',
            field=models.BooleanField(default=False, help_text='Also show it on the product page itself, next to Buy now / Add to bag.'),
        ),
    ]
