# Generated by Django 5.2.17 on 2026-10-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_inlineeditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='whatsapp_only',
            field=models.BooleanField(default=False, help_text='WhatsApp-only store: checkout offers only "Order on WhatsApp" (no online payment or COD).'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='whatsapp_order_enabled',
            field=models.BooleanField(default=False, help_text='Offer "Order on WhatsApp" as a checkout option: the order is saved in the dashboard, then the shopper sends it to your WhatsApp number.'),
        ),
    ]
