# Generated by Django 5.2.17 on 2026-09-04 15:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_product_catalog_prod_feed_idx_and_more'),
        ('orders', '0003_order_customer'),
        ('projects', '0006_project_is_b2b_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_listing', to='catalog.product')),
                ('seller_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_listings', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_project_name', models.CharField(blank=True, max_length=120)),
                ('source_product_title', models.CharField(blank=True, max_length=220)),
                ('wholesale_price_at_import', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('markup_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('buyer_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_imports', to='projects.project')),
                ('local_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_import', to='catalog.product')),
                ('seller_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_sales', to='projects.project')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='b2b.b2blisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BOrderLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_title', models.CharField(blank=True, max_length=220)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('wholesale_unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], db_index=True, default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payout_ref', models.CharField(blank=True, max_length=120)),
                ('ship_status', models.CharField(choices=[('pending', 'Awaiting shipment'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], db_index=True, default='pending', max_length=10)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('courier', models.CharField(blank=True, max_length=120)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('ship_to_name', models.CharField(blank=True, max_length=200)),
                ('ship_to_phone', models.CharField(blank=True, max_length=32)),
                ('ship_to_address', models.JSONField(blank=True, default=dict)),
                ('buyer_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_payables', to='projects.project')),
                ('import_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='b2b.b2bimport')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_ledger', to='orders.orderitem')),
                ('seller_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_receivables', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='b2blisting',
            index=models.Index(fields=['seller_project', 'is_active'], name='b2b_b2blist_seller__0daf8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='b2bimport',
            constraint=models.UniqueConstraint(fields=('buyer_project', 'listing'), name='uniq_b2b_import_per_listing'),
        ),
        migrations.AddIndex(
            model_name='b2borderledger',
            index=models.Index(fields=['seller_project', 'ship_status'], name='b2b_b2borde_seller__52ff99_idx'),
        ),
        migrations.AddIndex(
            model_name='b2borderledger',
            index=models.Index(fields=['buyer_project', 'status'], name='b2b_b2borde_buyer_p_5daa0c_idx'),
        ),
    ]
