# Generated by Django 5.2.17 on 2026-09-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_product_trashed_at_product_trashed_from_status'),
        ('projects', '0007_project_showcase_review_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('pinterest', 'Pinterest'), ('gbp', 'Google Business Profile')], max_length=16)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('target_id', models.CharField(blank=True, max_length=255)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('auto_share', models.BooleanField(default=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['provider'],
                'constraints': [models.UniqueConstraint(fields=('project', 'provider'), name='uniq_social_provider_per_project')],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('pinterest', 'Pinterest'), ('gbp', 'Google Business Profile')], max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('posted', 'Posted'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=12)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='catalog.product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'provider', 'product'), name='uniq_social_post_per_product_provider')],
            },
        ),
    ]
