# Generated by Django 5.2.17 on 2026-08-27 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(db_index=True, max_length=40)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=12)),
                ('to_address', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=12)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('related_type', models.CharField(blank=True, max_length=60)),
                ('related_id', models.CharField(blank=True, max_length=40)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=120)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('email_provider', models.CharField(default='django', max_length=30)),
                ('email_config', models.JSONField(blank=True, default=dict)),
                ('sms_provider', models.CharField(default='null', max_length=30)),
                ('sms_config', models.JSONField(blank=True, default=dict)),
                ('disabled_events', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'verbose_name': 'notification settings',
                'verbose_name_plural': 'notification settings',
                'constraints': [models.UniqueConstraint(fields=('project',), name='uniq_notifsettings_per_project')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('order_confirmation', 'Order confirmation'), ('payment_confirmation', 'Payment confirmation'), ('shipment', 'Shipment dispatched'), ('delivery', 'Delivered'), ('order_cancelled', 'Order cancelled'), ('refund', 'Refund processed'), ('welcome', 'Welcome'), ('password_reset', 'Password reset'), ('low_stock_alert', 'Low stock alert')], max_length=40)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=12)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'ordering': ['event', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('project', 'event', 'channel'), name='uniq_notiftemplate')],
            },
        ),
    ]
