# Generated by Django 5.2.17 on 2026-09-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='wa_language',
            field=models.CharField(blank=True, default='en_US', max_length=12, verbose_name='WhatsApp template language'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='wa_template_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='WhatsApp template name'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
