# Generated by Django 5.2.17 on 2026-09-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationtemplate_wa_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.CharField(choices=[('order_confirmation', 'Order confirmation'), ('payment_confirmation', 'Payment confirmation'), ('shipment', 'Shipment dispatched'), ('delivery', 'Delivered'), ('order_cancelled', 'Order cancelled'), ('refund', 'Refund processed'), ('welcome', 'Welcome'), ('password_reset', 'Password reset'), ('low_stock_alert', 'Low stock alert'), ('cart_abandoned', 'Abandoned cart'), ('trial_ending', 'Trial ending soon')], max_length=40),
        ),
    ]
